### ISSUE TITLE
Could use a sample TrumpBSQuotes.txt

### ISSUE THREAD

**Issue by mrdrozdov** [killianlevacher/TrumpBSQuoteRNNGenerator#1]
Can't run the code without some sample input. Generating my own input file, but would be nice to know that it matches some expected format.

**Comment by killianlevacher** [comment]
Hi Andrew,
Apologies for the delay. Actually yes of course thanks for pointing that out. Hadn't realised it wasn't in my last commit. Will add it now for you. Cheers :-)

**Comment by mrdrozdov** [comment]
Thanks! Read two things today that made me think of this:

1. http://www.thedailybeast.com/articles/2016/04/29/the-daily-show-premieres-rap-video-using-only-donald-trump-quotes.html (obviously), and
2. http://fusion.net/story/295515/quora-poetry-silicon-valley
