### ISSUE TITLE
Additional Training Details

### ISSUE THREAD

**Issue by mrdrozdov** [killianlevacher/TrumpBSQuoteRNNGenerator#3]
Have a few questions!

- How much data was used to generate the output seen in the blog post?
- Approx. how long does training take?
- Approx. how many epochs until we can expect to start seeing output that sort of makes sense.

**Comment by killianlevacher** [comment]
Hi Andrew, 

In continuation to the other issue you raised, if you have a quick look at the file with the Tweets collected by the NYT, it's actually relatively small. 

So the training ends up being quite fast and the issue you will find is that it will overfit to the data quite fast.

I made a change to the code and replaced the tokens from characters to words instead in another version. Might push it up.

Killian

**Comment by mrdrozdov** [comment]
👍
