### ISSUE TITLE
Error when running on Tensorflow 0.8.0

### ISSUE THREAD

**Issue by aewhatley** [killianlevacher/TrumpBSQuoteRNNGenerator#4]
When I tried running your code in Tensorflow 0.8.0, I got the following error message:

Data total tokens: 35709 tokens
Data vocabulary size: 85 tokens
Training Data total tokens: 32138 tokens
Validation Data total tokens: 1784 tokens
Test Data total tokens: 1784 tokens
----------------------------------------
Traceback (most recent call last):
  File "RunTrumpBSGenerator.py", line 112, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "RunTrumpBSGenerator.py", line 30, in main
    training_model = TrumpBSModel(bs_reader.vocabularySize,config_param=config)
  File "/Users/alexwhatley/Google Drive/Programming/TrumpBSQuoteRNNGenerator/RNN_Model.py", line 47, in __init__
    self._final_state = states[-1]
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 163, in _SliceHelper
    raise NotImplementedError("Negative indices are currently unsupported")
NotImplementedError: Negative indices are currently unsupported

**Comment by killianlevacher** [comment]
Hi, yes I've recently noticed this as well. It looks like they've changed something in the underlying implementation. I'll try and update the code as soon as I can to their latest version

**Comment by ikhlestov** [comment]
I've found the solution for tensorflow 0.9 - as per source code now rnn returns not all states but only last state

**Comment by ikhlestov** [comment]
I've added #5

**Comment by killianlevacher** [comment]
@aewhatley, @ikhlestov Thanks a mil lads for your input. Looking at this issue was on my task list for a while and I never got to it. Really appreciate your input on this.

Enjoy the week end,

Cheers,
